import { index, integer, pgTable, real, text, uniqueIndex } from "drizzle-orm/pg-core";

export const routes = pgTable("routes", { id: text().primaryKey(), shortName: text("short_name"), longName: text("long_name"), color: text(), routeType: integer("route_type") }, (table) => [index("routes_short_name_idx").on(table.shortName), index("routes_route_type_idx").on(table.routeType)]);
export const stops = pgTable("stops", { id: text().primaryKey(), name: text().notNull(), latitude: real().notNull(), longitude: real().notNull(), parentStation: text("parent_station"), platformCode: text("platform_code") }, (table) => [index("stops_name_idx").on(table.name)]);
export const trips = pgTable("trips", { id: text().primaryKey(), routeId: text("route_id").notNull(), serviceId: text("service_id").notNull(), headsign: text(), blockId: text("block_id"), shapeId: text("shape_id") }, (table) => [index("trips_route_idx").on(table.routeId), index("trips_service_idx").on(table.serviceId), index("trips_shape_idx").on(table.shapeId)]);
export const shapes = pgTable("shapes", { shapeId: text("shape_id").notNull(), sequence: integer().notNull(), latitude: real().notNull(), longitude: real().notNull() }, (table) => [uniqueIndex("shapes_sequence_idx").on(table.shapeId, table.sequence)]);
export const stopTimes = pgTable("stop_times", { tripId: text("trip_id").notNull().references(() => trips.id), stopId: text("stop_id").notNull().references(() => stops.id), arrival: integer().notNull(), departure: integer().notNull(), sequence: integer().notNull(), platformCode: text("platform_code") }, (table) => [uniqueIndex("stop_times_trip_sequence_idx").on(table.tripId, table.sequence), index("stop_times_stop_departure_idx").on(table.stopId, table.departure)]);
export const transfers = pgTable("transfers", { id: integer().primaryKey().generatedAlwaysAsIdentity(), fromStopId: text("from_stop_id").notNull(), toStopId: text("to_stop_id").notNull(), fromTripId: text("from_trip_id"), toTripId: text("to_trip_id"), type: integer().notNull(), minimumSeconds: integer("minimum_seconds") }, (table) => [index("transfers_trip_ids_idx").on(table.fromTripId, table.toTripId)]);
export const calendars = pgTable("calendars", { serviceId: text("service_id").primaryKey(), monday: integer().notNull(), tuesday: integer().notNull(), wednesday: integer().notNull(), thursday: integer().notNull(), friday: integer().notNull(), saturday: integer().notNull(), sunday: integer().notNull(), startDate: text("start_date").notNull(), endDate: text("end_date").notNull() });
export const calendarDates = pgTable("calendar_dates", { serviceId: text("service_id").notNull(), date: text().notNull(), exceptionType: integer("exception_type").notNull() }, (table) => [uniqueIndex("calendar_dates_service_date_idx").on(table.serviceId, table.date)]);
